# Generated by Django 3.1 on 2020-08-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200829_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='seller',
        ),
    ]
