# Generated by Django 3.1 on 2020-08-29 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='last_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coment',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_coments', to='auctions.auction'),
        ),
    ]
