# Generated by Django 3.1 on 2020-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200829_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.FilePathField(path='static/auctions/media'),
        ),
    ]
