# Generated by Django 3.1 on 2020-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200829_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.FilePathField(blank=True, null=True, path='/static'),
        ),
    ]
