# Generated by Django 3.1 on 2020-08-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200829_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.FilePathField(blank=True, null=True, path='images_path'),
        ),
    ]
