# Generated by Django 3.1 on 2020-08-30 05:48

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200829_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_image',
            field=models.FilePathField(blank=True, null=True, path=auctions.models.images_path),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category_name',
        ),
        migrations.AddField(
            model_name='auction',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_with_category', to='auctions.category'),
        ),
    ]
