# Generated by Django 3.1 on 2020-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200830_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_list',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
