# Generated by Django 3.1 on 2020-09-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watch_list_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='auction',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
    ]
